// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetMetrics():Promise<Record<string, any>>;

export function GetProfiles():Promise<Array<main.Profile>>;

export function IsRunning():Promise<boolean>;

export function SaveProfile(arg1:main.Profile):Promise<void>;
